---

  - name: Install nginx
    become: yes
    apt: name=nginx state=installed

  - name: Install openjdk
    become: yes
    apt: name={{item}} state=installed
    with_items:
      - openjdk-8-jre
      - openjdk-8-jdk

  - name: download tar file from url
    become: yes
    get_url:
      url: http://ftp.naz.com/apache/tomcat/tomcat-8/v8.5.39/bin/apache-tomcat-8.5.39.tar.gz
      dest: /root/
 
  - name: Extract contents from tomcat
    become: :yes
    unarchive:
      src: /root/apache-tomcat-8.5.39.tar.gz
      dest: /root
      remote_src: yes 
  - name: change directory and execute command
    command: chdir=/root/apache-tomcat-8.5.39 ./bin/startup.sh





