---

  - name: Install nginx
    become: yes
    apt: name=nginx state=installed

  - name: Copy nginx.conf from repo /etc/nginx
    template: src="templates/nginx.conf" dest=/etc/nginx/nginx.conf
    become: yes

  - name: Copy default file from repo to nginx folder
    template: src="templates/default" dest=/etc/nginx/sites-available/default
    become: yes

  - name: Restart nginx
    service:
      name: nginx
      state: restarted
    become: yes

  - name: Install openjdk
    become: yes
    apt: name={{item}} state=installed
    with_items:
      - openjdk-8-jre
      - openjdk-8-jdk

  - name: download tar file from url
    become: yes
    get_url:
      url: https://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.40/bin/apache-tomcat-8.5.40-fulldocs.tar.gz
      dest: /root/
 
  - name: Extract contents from tomcat
    become: :yes
    unarchive:
      src: /root/apache-tomcat-8.5.39.tar.gz
      dest: /root
      remote_src: yes 

  - name: Extract contents from tomcat
    become: :yes
    command: mv /root/apache-tomcat-8.5.39 /root/apache-tomcat
    
  - name: change directory and execute command
    command: chdir=/root/apache-tomcat ./bin/startup.sh





