---
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
      update_cache: yes
    become: yes

  - name: Install required packages for k8
    apt:
      pkg: '{{item}}'
      state: present
      update_cache: yes
    become: yes
    with_items:
      - apt-transport-https
      - docker.io
      - git
      - python-pip


  - name: Start and enable docker
    systemd: state=started name=docker
    become: yes

  - name: Enable docker
    systemd: enabled=yes name=docker
    become: yes

  - name: Install docker-py using pip
    pip:
      name: docker-py
      state: present
    become: yes

  - name: get key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present
    become: yes

  - name: Create sources.list.d file for Kubernetes
    copy:
      content: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
      dest: /etc/apt/sources.list.d/kubernetes.list
      force: yes
    become: yes

  - name: Install Kubernetes applications
    apt:
      pkg: '{{item}}'
      state: present
      update_cache: yes
    become: yes
    with_items:
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni

  - name: just force systemd to reread configs (2.4 and above)
    systemd:
      daemon_reload: yes

  - name: just force systemd to reread configs (2.4 and above)
    systemd:
      name: kubelet
      state: restarted
  - name: Kubeadm reset
    shell: "kubeadm reset --force"
    ignore_errors: True

  - name: Init k8 Master and pipe the output to a text file - output.txt
    command: kubeadm init --pod-network-cidr=10.244.0.0/16 
    become: yes

  - name : Apply flannel
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml

  - name: Taint master node
    command: kubectl taint nodes --all node-role.kubernetes.io/master-
  
  - name : Apply metallb
    command: kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.7.3/manifests/metallb.yaml
  
  - name: Copy metallb config file
    copy: src=templates/metal.yaml dest=/root/metal.yaml
    become: yes
 
  - name: Copy blue-green deployment file
    copy: src=templates/bluegreen.yaml dest=/root/bluegreen.yaml
    become: yes
  
  - name: Apply metallb
    command:  kubectl apply -f /root/metal.yaml

  - name: Apply bluegreen 
    command:  kubectl apply -f /root/bluegreen.yaml

  - name: Clone dockerhub-webhook reciever repo
    git:
      repo: https://github.com/ashwinrisbood/dockerhub-webhook.git
      dest: /var/www/dockerhub-webhook
      force: yes
      
  - name: Install npm packages 
    npm: path=/var/www/dockerhub-webhook

  - name: "Install forever (to run Node.js app)."
    npm: name=forever global=yes state=present
 
  - name: "Check list of Node.js apps running."
    command: forever list
    register: forever_list
    changed_when: false

  - name: "Start example Node.js app."
    command: forever start /var/www/dockerhub-webhook/index.js
    when: "forever_list.stdout.find('/var/www/index.js') == -1"
