---

  - name: Install redis by downloading tar file from url
    become: yes
    get_url:
      url: http://download.redis.io/redis-stable.tar.gz
      dest: /root/
 
  - name: Extract contents from tomcat
    become: :yes
    unarchive:
      src: /root/redis-stable.tar.gz
      dest: /root
      remote_src: yes 

  - name: change directory and execute command
    command: chdir=/root/redis-stable/src redis-server 

  - name: type command make 
    
