checkbox_name: "checkbox_build"
iTrust_name: "iTrust_build"
jenkins_password: "Jenkins@6"
<<<<<<< HEAD
private_key: 
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEA9njfjPet0eiZKP0Ubvj+MUnGe3RhC/KoLxW5EBJpM1s3pnFX
  ce6t+/eOu92vE2Ax5xUBqfpScZj9WHimRaTg/kLj+hIX2QcuA9GSLLtAoLnUMCF1
  uU3xOcU96ORvdTCk9ph6R9FQgw+VGBNjc9JpGNZNFfgQaosNN8Pc4+f7JduDf2oZ
  o+s3120vHPU+KVAJ8dSqH/s7qua3cufgnKEZGyVBgpiJ4WowIksN9hpqKNNHoe7B
  YUdCPwQRtWqfsrY0YfJUulc1bWtZORcdDmMqlYx2YIeXpyCGRZDtuC4WknOXdtIR
  /erIBPzKN16QiNsN0+Dzagpj/JCP1roXW7P1dQIDAQABAoIBACax6V7nT6nB27Hc
  scWOX9H7JCcjqUzH5vGldm14hn2il4URDEp9z2Dch9MkxaTEGHGQEbfO7fyZqUSn
  hGswrIYemE4dYxMWlnnRACL3rvjM0+xOhH34J6QLPGIA4yLB5VQ1shTuXraEzsJ9
  4MJBSXC1zFpjnKgtdoDHxjkdpYdWtVnJAqDWI844LyDlv0Xe1HmddjNYfWNAtmL5
  V5Q/ybl62XHTNAioKwPjHsQi1nUnEXHWepfnpuhCgdi/MsVuyVTNTsEY++5AlJ+i
  DToSkl0KY0RhQ0TLLTAEmwgHZmBSZ1Vopwbfg9hfuIsYLpvj7v+DYwnEGPi75twb
  qgP97yECgYEA/CtZQhtgwFpFPVBywhotwTaozOJC2FrKAg9L9wmLwh5o98vu9gQU
  fReb7t9LR/ZrR7w6bG1QkuKr+OUwL1+tH4arFiLXxal+DP+nf7V+nVKycNybjj3A
  VffANVFMX8tCz/O3Ifvu99u6v691LX0tPyGpgRXU8yby+mcmkvj3nvkCgYEA+jde
  fCyi7wILnxFVXwhWv9maMN7oHcCSTgqd3T5nha6etNWGBrfvBh4pmBQoHjD5lodh
  9xevwQ2iqZbaCYAn1xZhKBberhxwy+7TfX8dazVybz1+6u5acRBwbgq2QwOVAiLk
  Fs8WsQmx4g3got0J3qI7wx0Rt9+rrSwJTOjlHV0CgYEAmZUhQNUB4UVZhFV5/2QI
  V/QdbOOlSLZK8GQ2pRfoSetRjRJk0Ot9Ow7lBuByrjqT7lXi02TkvQFXMjkMVt4T
  x+6yRsIj3pwzTGFst6hnnBPg4EJMb56GhRVmuFJyjKl0YMkT0ZvqWIU4QUTwvirO
  IvQyk48japBfTkkCwmLmFakCgYEAlUUc1+VlGkLVHgMgM/5sii1NoCQKw10Tqv0I
  ammFJqoiweyz9SQbs0GhPLmhqUk8TIHdfqQh1IDG7ncxAgPzQIx4T4s9Mw+Cdxa2
  EqMXsNKEvzonkg255MOS3wMC8n2bklewTK8kcV9AQIRY47AL6EZOcrrPzCriZv/j
  WH+D130CgYAxX+NKNGLWZNwYXk6a0N3OPuESl0cxvL0IFs1al3QKL8MFX7hfRSE5
  3INcTNZJhvG6WpIcUnoAAIGnd8BBmcHlZUuYwlM2gAPRuCMh2khYaukIZgowafdA
  j3oQEMfHAdVlQY98F/ck4hK5nilelUalq9q+nWhnGretxLvYHgj8PA==
  -----END RSA PRIVATE KEY-----

=======
private_key: -----BEGIN RSA PRIVATE KEY-----
            MIIJKAIBAAKCAgEAqPmEYSNho56PuTQ/jf6Qb78Owb44ujhLWYFCryX/D/az3FAk
            fMOw6Qz06S0jOLKQaiMKBDNQkEZx/Mf1H74a+dbVP++AOCdjIARIwpSPDOWfIqmI
            Q1n6EcsKP9rgda6zxyAiDO9ei0RRiA6Kp7fpXh1OMHHx5hzWvPyqgubTcXff1QcX
            r3odAiLu/wWt/1FbZ+gk2NrBjKNJiZNCI8yLCuNk4ES+2Tk0H26NU3dw6TgnbdNs
            X7ecVwpPSrkcMK43bcmWz/J/MXO/2HEZNKbMBVYjXxGlORG+Nvg069DoQoGnRg/b
            n8SW0oeLctlZkcnEAX49NFakDtszzS9ru+hH5DBCP07KVWp7DAoXkbbdwuUCUAr9
            IF57Q0rp84CDr24EoXOuOHiK5lf5IdKC2JFvhYvNM6sf3SHSjHOzqVyv7piW9fGq
            NiAbQaE4ja+XJWtV3qw8GVyRKerDyZUo2vcTW9MsNDwH8TIirEf348pmeRO3T2mI
            0t2/iyMsY8S/hkq/GUS/t2h+5WLHQGkMHpHrMWjGVEnyg8EVpOVLxPNYKQllpIHE
            3KsQhrogQnb4gVPPMl3w7haHYnYGEyd/STPb94Crr5SQLUWgW10iemE42p36M5Zq
            WjWCJh1D3qKGNtL5aJZl87NpZWSPoDOvBmaZ5pd3p/NCyWJ4p9upIoFjPVkCAwEA
            AQKCAgBRyAn5Fa3BChIXmiEUcVuoqfjTbmR4RJy7YiNLMAGl0Uo13Bf8xp3N/bZf
            ULhWTZ41sGW9qLRaT64FoSWTSmg1+XNWsW0GQJHqQgiRHGOr40rE9PZ9WoP8rp90
            TlQKwRZDztqMFiJVFyi6yAb1q75oDZj1O4DPVa/c4hEIr/0wUstjiD4/cMOvcAbq
            KO6QvuiVfrauuhmpHrKNwlbliq7VAz+kh8Ey00vV1qTR++ILDmGO9x/hp7UkL1o3
            GSZ6rSconMPAO2ayIYp9kCeZ4wylnI4cCidEWsEMS88ZPw/aeHPkJfKu/e/dTzr/
            yBBgzh1ud5HZzgEzK4aDzWrAFGkOT6Oa3OuqCPmYGZZ/Z8H/lSvRxcnVG9UyjFpe
            yjXhnBfsJzhjFLqyIQfoSO31sbNJkmxQ1XmMEOdYwqmK8nhCSJM5WiUDZQ/X6hpc
            ophsS4iGExqqB5/LpodZunDdrxJbljD86iJUp34xCs1LPHqcaB3QmUEppIfYrMUk
            crUm6OhUy/u5IcKcpeGGATd26XIi9ljs1GwgSjNd1ejO42HLQBXq569bfhhwDfEf
            rVoCM9h6jMeiZQXNsOgf4f7d7T8aPHaOSipJVzoEVyM21K/CDIUtdX8SENeDZaEc
            Ob7cKlVDuuZkfk1v/KVDhEGVYBpOYPAiHnedSiYoL6J/9RKTvQKCAQEA1YvF0aho
            //O55rk5uGOwdcZ9FM+QNoJNCILGDHWlo/AQdNwd1eWLH0Yap4uYn/WJT50VwcL0
            efDyToLDX7GLAZtc/6eUJ7glhQ0u0dUBcIlH6Z8KBZ8BVJIR7i3V2c9FBh0jmLF1
            BvO5ulcGizv3r8+vcVqVU5YF33vaWlcV4iP1GeH1QzAru5wLyKtLr8SrZZ9JL5xR
            5xxmNvvxyUmL7tVCoclyMR9X0qluwGriSOziBCL4mUuhvK5UElgmvFFa2kSP/gEx
            +D+DyY8FZ3p8NtdZWYAEs+6HXekxTfD6EhbkfB3AWYeu/N3ETRTX64tS+twYSGQT
            EPQZNEt34qOKIwKCAQEAypFUD1cWMaHGzRgaXODqmGZj6uwb8kQ2MUDKlJloUt6H
            p/9779RYmcR1Yo5W7H0lmcVH12kE0co7Sco7YtSPR1wLgicyjR+Sq+zxyetwqVEu
            LDsmraL3BVaTMqRnAaWpHQlbp+NIeeZcnuW3b8EBAEKPy3xujGsHuZ9miumf45qq
            4DbsqMB296yhiXQB1yhWDSEHdcnBfHN8aawDEkp6cssdOB85lmBZpwqAuXxH0l/W
            Qrhohq7MH1X7CDefwh23Pz4b9V7XxzirNaq7zFs6ceSNuHv11bHV5QRR5YsPh+KG
            CdEDzMuao/1/df0TsiztYdC3K2aYaOEejyGv4sH8UwKCAQBJ8jqwHScu6pEHSkCo
            jyy9u9v4Zt/DYF+YgOBf1CVlnW21abuTJAeG7tmwBvD1AytnPDgafo314++kLDfH
            XU2LYudTSA5Pqr6jUitSUfZLp94VEhOAWs01Ide/qHOTFukJ8vEuoNSrcZ5w3k3P
            zRY59SsFj56B8UNbXiIAgoN7aYQoUEyD1ZxvPNv/wwFUfj/z0rKfH/xkkTr780aI
            s0UXkRWfvIgkZnwc4LsPOnPdWNnzIMEBJGV/VsaaC5huQaW6S1+pT3SkSCo0k6gF
            ay60NuIj0ebO/9w0Mtn16WpO9UptiEfhONDpk0m0f3E9iWNUpv5pou3PQxevOirr
            ekINAoIBACfC3v0j2vdjCeK4GHSisWm4r2QtdE7ZlMmWLi187z1U8MvJGkq5I6sL
            JP9zcRx6dCb60l81/fwv9fNF/uInVvhq2NdzWjjZObEFkXBRBow1oxqLgcwTcOlb
            VQlbu9xW6BsK+zK5KkDDNur5rEgDWm7yoccPZaOqXpnQ8A/US84hTek03r9BCBkV
            iZ+xZasV/84T7aLxN0l2YbVcTj4I4IAn3lRlzKf3waFILnw6KN7icOwnxlypcuez
            uNKkGHfB3XZMerBvLWutc+3U1YgHYDF661aK/nYzsgiCEJE9+o5xqF3E6ToJvRDz
            cVF3m6Ydq3rHvSyHtuLfTWBK/HtGGIECggEBAMXM4KSngNKpTCApjFpvEI3TvJtp
            8A2Mvhj/M0pXkBIDxcBFqF/0cYXnGpPc/AgPekh/vEyOOGOSh3dplswXie231Bod
            6h8d2I8Pn7dTl/Po1jSMpwXDQu2PlrTr9+zcRZfGgJc4f6nU4PeD5CdUyBCtvJsG
            DrnJ2NVUhgRXkCwn8Whe+le9GUKo3athetUZ7lKrbxz0bs2KHniUURpWltfmG+EM
            g08w319Gyq9XEdfcdyoxUDCoiyhyV1AYx+tHiMYidkadnKJVXHUC2YapTKtEfK1o
            cJmno7sstGUNY0o6+sPve4CIECE4NSMCQdE/K1JPAvF+yZwHlVUZacX+a5M=
            -----END RSA PRIVATE KEY-----
>>>>>>> 9aa3fd37a2b217f6eb365833b30df48c80a349d4
jenkins_plugins:
  - git
  - job-dsl
  - workflow-aggregator 
  - workflow-cps
  - pipeline-maven
  - maven-plugin
  - checkstyle
  - findbugs
  - analysis-collector
  - warnings-ng
  - analysis-core
