- hosts: localhost

  tasks:
  - name: copy DB properties
    template:
      src: templates/db.properties
      dest: ./iTrust2/iTrust2-v4/iTrust2/src/main/java/db.properties

  - name: copy email properties hook
    template:
      src: templates/email.properties
      dest: ./iTrust2/iTrust2-v4/iTrust2/src/main/java/email.properties

  - name: copy iTrust hook
    template:
      src: templates/iTrust_post-commit
      dest: ./iTrust2/iTrust2-v4/.git/hooks/post-commit
      mode: +x
  - name: copy checkbox.io hook
    template:
      src: templates/checkbox_post-commit
      dest: ./checkbox.io/.git/hooks/post-commit
      mode: +x
  - name: copy pom.xml
    template:
      src: templates/pom-data.xml
      dest: ./iTrust2/iTrust2-v4/iTrust2/
  - name: copy findbugs-include.xml
    template:
      src: templates/findbugs-include.xml
      dest: ./iTrust2/iTrust2-v4/iTrust2/

  - name: copy itrust JenkinsFile
    template:
      src: templates/iTrustJenkinsFile
      dest: ./iTrust2/iTrust2-v4/

  - name: copy checkbox JenkinsFile
    template:
      src: templates/checkboxJenkinsFile
      dest: ./checkbox.io/
