- hosts: all
  tasks:
  - name: Fetch 100 log files
    fetch:
      src: /var/lib/jenkins/jobs/iTrust_build/builds/{{item}}/log
      dest: /Project/ansible-srv/logs/{{item}}
      flat: yes    
    with_sequence: start=25 end=50 stride=1
